# Generated by Django 3.2.9 on 2021-11-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAdmin',
        ),
    ]
