# Generated by Django 3.2.9 on 2021-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_productadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebay_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('url', models.TextField()),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
    ]
